export const config = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  JWT_SECRET_KEY: process.env.NEXT_PUBLIC_JWT_SECRET_KEY,
  BACKEND_URL:process.env.NEXT_PUBLIC_BACKEND_URL,
  FRONTEND_URL:process.env.NEXT_PUBLIC_FRONTEND_URL,
};
